language: java

env:
  - MAVEN_OPTS="-Xmx2048m -Xms512m -XX:MaxPermSize=512m"

jdk: 
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install: mvn clean install -B -DskipTests=true -s /home/travis/build/richfaces/richfaces/buildhive-settings.xml

script: mvn clean verify -Dintegration=wildfly82 -Dsmoke -s /home/travis/build/richfaces/richfaces/buildhive-settings.xml -Darquillian.maven.settings=/home/travis/build/richfaces/richfaces/buildhive-settings.xml

cache:
  directories:
  - '$HOME/.m2/repository'

sudo: false
